python run.py --dataset MNIST --attack_method LabelFlipping --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset MNIST --attack_method LabelFlipping --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset MNIST --attack_method SignFlipping --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset MNIST --attack_method SignFlipping --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset MNIST --attack_method Noise --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset MNIST --attack_method Noise --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset MNIST --attack_method ALIE --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset MNIST --attack_method ALIE --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset MNIST --attack_method MinMax --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset MNIST --attack_method MinMax --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset MNIST --attack_method IPM01 --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset MNIST --attack_method IPM01 --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset MNIST --attack_method IPM100 --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset MNIST --attack_method IPM100 --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset MNIST --attack_method Backdoor --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset MNIST --attack_method Backdoor --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset MNIST --attack_method NoAttack --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset MNIST --attack_method NoAttack --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset FashionMNIST --attack_method LabelFlipping --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset FashionMNIST --attack_method LabelFlipping --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset FashionMNIST --attack_method SignFlipping --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset FashionMNIST --attack_method SignFlipping --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset FashionMNIST --attack_method Noise --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset FashionMNIST --attack_method Noise --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset FashionMNIST --attack_method ALIE --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset FashionMNIST --attack_method ALIE --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset FashionMNIST --attack_method MinMax --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset FashionMNIST --attack_method MinMax --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset FashionMNIST --attack_method IPM01 --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset FashionMNIST --attack_method IPM01 --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset FashionMNIST --attack_method IPM100 --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset FashionMNIST --attack_method IPM100 --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset FashionMNIST --attack_method Backdoor --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset FashionMNIST --attack_method Backdoor --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset FashionMNIST --attack_method NoAttack --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset FashionMNIST --attack_method NoAttack --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset CIFAR10 --attack_method LabelFlipping --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset CIFAR10 --attack_method LabelFlipping --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset CIFAR10 --attack_method SignFlipping --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset CIFAR10 --attack_method SignFlipping --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset CIFAR10 --attack_method Noise --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset CIFAR10 --attack_method Noise --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset CIFAR10 --attack_method ALIE --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset CIFAR10 --attack_method ALIE --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset CIFAR10 --attack_method MinMax --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset CIFAR10 --attack_method MinMax --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset CIFAR10 --attack_method IPM01 --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset CIFAR10 --attack_method IPM01 --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset CIFAR10 --attack_method IPM100 --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset CIFAR10 --attack_method IPM100 --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset CIFAR10 --attack_method Backdoor --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset CIFAR10 --attack_method Backdoor --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset CIFAR10 --attack_method NoAttack --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 2
python run.py --dataset CIFAR10 --attack_method NoAttack --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 2
