python run.py --dataset MNIST --attack_method LabelFlipping  --defense_method FedAvg --iid False --alpha 0.1 --given_size 4096 --gpu_id 0
python run.py --dataset MNIST --attack_method LabelFlipping  --defense_method FLUD --iid False --alpha 0.1 --given_size 4096 --gpu_id 0
python run.py --dataset MNIST --attack_method LabelFlipping  --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 0
python run.py --dataset MNIST --attack_method LabelFlipping  --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 0
python run.py --dataset MNIST --attack_method LabelFlipping  --defense_method FedAvg --iid False --alpha 10 --given_size 4096 --gpu_id 0
python run.py --dataset MNIST --attack_method LabelFlipping  --defense_method FLUD --iid False --alpha 10 --given_size 4096 --gpu_id 0
python run.py --dataset FashionMNIST --attack_method LabelFlipping  --defense_method FedAvg --iid False --alpha 0.1 --given_size 4096 --gpu_id 0
python run.py --dataset FashionMNIST --attack_method LabelFlipping  --defense_method FLUD --iid False --alpha 0.1 --given_size 4096 --gpu_id 0
python run.py --dataset FashionMNIST --attack_method LabelFlipping  --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 0
python run.py --dataset FashionMNIST --attack_method LabelFlipping  --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 0
python run.py --dataset FashionMNIST --attack_method LabelFlipping  --defense_method FedAvg --iid False --alpha 10 --given_size 4096 --gpu_id 0
python run.py --dataset FashionMNIST --attack_method LabelFlipping  --defense_method FLUD --iid False --alpha 10 --given_size 4096 --gpu_id 0
python run.py --dataset CIFAR10 --attack_method LabelFlipping  --defense_method FedAvg --iid False --alpha 0.1 --given_size 4096 --gpu_id 0
python run.py --dataset CIFAR10 --attack_method LabelFlipping  --defense_method FLUD --iid False --alpha 0.1 --given_size 4096 --gpu_id 0
python run.py --dataset CIFAR10 --attack_method LabelFlipping  --defense_method FedAvg --iid False --alpha 1 --given_size 4096 --gpu_id 0
python run.py --dataset CIFAR10 --attack_method LabelFlipping  --defense_method FLUD --iid False --alpha 1 --given_size 4096 --gpu_id 0
python run.py --dataset CIFAR10 --attack_method LabelFlipping  --defense_method FedAvg --iid False --alpha 10 --given_size 4096 --gpu_id 0
python run.py --dataset CIFAR10 --attack_method LabelFlipping  --defense_method FLUD --iid False --alpha 10 --given_size 4096 --gpu_id 0
